import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Providers } from '@/providers';
import { Bounce, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='w-screen h-screen bg-gray-800'>
        <ToastContainer position='top-center' transition={Bounce} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
